import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import AnalyticsCard from "@/components/AnalyticsCard";
import Layout from "@/components/Layout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="text-black bg-white
      ">
      <Layout>
        <Header />
        <div className="flex w-full">
          <div className="w-3/4">
            {children}
          </div>
          <AnalyticsCard />
        </div>
      </Layout>
      </body>
    </html>
  );
}
